### ISSUE TITLE
add ability to show/hide columns

### ISSUE THREAD

**Issue by jlgerber** [evancz/elm-sortable-table#1]
Being able to dynamically show/hide columns via a context sensitive menu would be great. However, being able to pass in a list of visible columns and maintain that in the model would be nice too. Seems like it would be pretty simple...

And once you have that list in the model, why drag and drop reordering of columns is not that far off :)

**Comment by evancz** [comment]
This sounds like a very specialty kind of table. I don't think it'll make sense to make this library more complex to support a very custom scenario. You'll probably have better results if you do it yourself.
