### ISSUE TITLE
Accessing the sorted rows

### ISSUE THREAD

**Issue by karls** [evancz/elm-sortable-table#17]
Hi,

I have a use case where I want the user to be able to select rows in bulk. This is almost identical to what happens in GMail where you can select several consecutive rows by holding down the shift key. 

I have implemented this "select in bulk" and that works very well. The problem arises when the table is sorted by one of the columns. Because I keep track of the selected rows using the row indices into the table input list, whenever the ordering of rows differs from the original ordering of the list, by sorting on one of the columns, for example, bulk selection via holding down the shift key behaves very unexpecedly.

My question is -- would it possible to access the sorted table data, which currently is hidden from the library user? Or perhaps there is something I'm missing in the implementation of my "select in bulk" functionality, i.e perhaps using row indices is the wrong approach?

I've put together a short video demonstrating the behaviour here http://d.pr/v/MWXV.

**Comment by Qqwy** [comment]
@karls There currently is an `getSortedData`-function available.

 https://package.elm-lang.org/packages/billstclair/elm-sortable-table/latest/Table#getSortedData 

(Note: it's only available on the new Elm 0.19 fork of this library)

**Comment by evancz** [comment]
This package is deprecated. Community members will be managing forks and alternates from 0.19 and above.
