### ISSUE TITLE
Table rows are mis-ordered

### ISSUE THREAD

**Issue by dimbleby** [evancz/elm-sortable-table#2]
I've put together a repo demonstrating the issue [here](https://github.com/dimbleby/sortable-table-bug) with instructions in the `README` - let me know if this is unclear.

Note that it does take exactly the described clicks, in that order, to demonstrate the problem - but it's then completely reproducible for me.

I find it hard to see how this _can_ be a bug in the `elm-sortable-table` code, but I guess this is the right place to start.

I'm using elm 0.17.1

**Comment by justinmimbs** [comment]
The reordering bug looks due to the way VirtualDom reorders keyed nodes. I opened an issue on virtual-dom: https://github.com/elm-lang/virtual-dom/issues/32

**Comment by evancz** [comment]
Great, thanks @justinmimbs! Let's follow along there instead.

**Comment by evancz** [comment]
Alright, the original issue should be resolved if you hard refresh on the examples hosted on this repo. Otherwise, if you rebuild your projects with virtual-dom 1.1.1 you should get the fix in anything else.

Thanks for the report!

**Comment by dimbleby** [comment]
ack - thanks both @evancz for the fix, and @justinmimbs for reducing my example to something more bite-sized
