### ISSUE TITLE
Unsafe column identification

### ISSUE THREAD

**Issue by grotsev** [evancz/elm-sortable-table#26]
https://github.com/evancz/elm-sortable-table/blob/bf632ced14aa6189a19a7a1272e46e514421bd5a/examples/2-travel.elm#L34

There is no column "Year" in this example. That is typo but I think as far as columns in config are not dynamic they may be enumerated in union type. Moreover union typed columns do i18n typesafe.

On the other hand this union type may model "column family" by accepting dynamyc arguments. Extending trip planner example:

```elm
type Mood -- column family index
  = Sad
  | Glad

type TripPlannerColumn
  = Name
  | Price
  | Rating
  | Time Mood -- column family
```

**Comment by Qqwy** [comment]
I believe this is on purpose:

The Table config can be changed at runtime to alter what columns are shown; this means a table might end up being 'sorted' by a table column that does not exist anymore, but this is handled by the implementation:

https://github.com/evancz/elm-sortable-table/blob/bf632ced14aa6189a19a7a1272e46e514421bd5a/src/Table.elm#L507-L515

Sorting by a column that does not exist anymore is a no-op, but it will not break the table :-).

**Comment by evancz** [comment]
This package is deprecated. Community members will be managing forks and alternates from 0.19 and above.
