### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by gaul** [evancz/elm-sortable-table#29]
Could elm-sortable-table provide pagination?  This could collapse long lists into multiple pages, e.g., 1 of 12, which users could navigate forward and back.  jQuery provides an example:

https://esimakin.github.io/twbs-pagination/

**Comment by Qqwy** [comment]
I have exactly this requirement.

We are working on a webshop-application, that will have multiple thousand products, so pagination is a must.

**Comment by evancz** [comment]
This package is deprecated. Community members will be managing forks and alternates from 0.19 and above.
