### ISSUE TITLE
Stable sort

### ISSUE THREAD

**Issue by wknapik** [evancz/elm-sortable-table#33]
The sorting should be stable, either w.r.t. the previous sort order, or the order of the list of row elements supplied.

For example, now, if I have a table with a `name` column and a `score` column and the score happens to be the same in most rows, sorting by score will change the order of those rows in a seemingly random way.

**Comment by wknapik** [comment]
Sorting by a tuple, like (score, name) is not a solution, because we may be sorting by score in ascending order, with the previous order by name being descending, so we end up changing the order seen by the user unnecessarily and unexpectedly.

**Comment by wknapik** [comment]
You can reproduce it here https://evancz.github.io/elm-sortable-table/presidents.html - sort by state descending, so you have everyone from Virginia at the top. You'll notice that the order of the presidents from Virginia is, apparently, random.

**Comment by wknapik** [comment]
Traced the issue to this https://github.com/elm-lang/core/issues/958.

**Comment by evancz** [comment]
Nice, will make that the canonical one. Thanks!
