### ISSUE TITLE
Storing the table state in the URL: Make Table.State non-opaque?

### ISSUE THREAD

**Issue by Qqwy** [evancz/elm-sortable-table#37]
I want to store the information of how the table currently is sorted in the URL, so that when users share the page with eachother, they look at the items in the same order.

However, currently:

- `Table.State` is opaque, so we cannot inspect it to find out how the table currently is sorted.
- There is no real `update` that takes a `msg` and returns a state. As explained [in the README](https://package.elm-lang.org/packages/billstclair/elm-sortable-table/latest/#about-api-design), the library  'cheats':

> I took some minor liberties with update to make the API a bit simpler. It would be more legit if Table.Config took a Table.Msg -> msg argument and you needed to use Table.update : Table.Msg -> Table.State -> Table.State to deal with it. I decided not to go this route because Table.Msg and Table.State would both allocate the same amount of memory and one version the overall API a bit tougher. As we learn from how people use this, we may see that the explicit update function is actually a better way to go though!

- There is no function to turn a `Table.State` into a `Maybe (String, Bool)` (which are the column name and an 'isReversed' boolean).
- There is no way to initialize the table with a reversed column; `Table.initialSort` only takes a `String`.

---

I think the best way to solve this is:

1. Add a function to turn a `Table.State` into a `Maybe (String, Bool)`.
2. Add an alternative to `Table.initialSort` (maybe named `Table.customizedInitialSort`?) with a type signature of `String -> Bool -> Table.State`. _(Reason to add an alternative is backwards-compatibility)_

**Comment by evancz** [comment]
This package is deprecated. Community members will be managing forks and alternates from 0.19 and above.
